### ISSUE TITLE
Version 0.1.0?

### ISSUE THREAD

**Issue by aaronchi** [flipsasser/addressabler#4]
It looks like version 0.1.0 of addressabler was never released to rubygems even though the documentation references it.

**Comment by edubkendo** [comment]
Looks like https://github.com/flipsasser/addressabler/blob/master/addressabler.gemspec#L30 could be to blame? I'm still encountering this problem trying to install it myself.

**Comment by mattp88** [comment]
1.9.3 error is still popping up.

**Comment by flipsasser** [comment]
Sorry guys. Can you upgrade to 0.1.1 and confirm it's fixed? https://github.com/flipsasser/addressabler/commit/4f3e5809abe5066e03906c730723f47d4daec8c2

**Comment by edubkendo** [comment]
That worked! thanks
